### ISSUE TITLE
MUSL adoption

### ISSUE THREAD

**Issue by dherrendoerfer** [wernsey/musl#1]
Hey Werner,
this is not an issue in the normal sense, but I'd like to pass on some thanks and praise:
I built the microME home computer prototype some time ago, and have been using MUSL as the basic interpreter for that, and I love it ! It's very versatile and easy to adopt, I may do some work on it to address some of the bigger differences to other basic dialects.
If you are interested, I'd like to offer you a prototype board with all the passives populated.
Cheers, 
Dirk

The microME project can be found here: https://github.com/dherrendoerfer/microme

**Comment by wernsey** [comment]
Hi Dirk,

Thank you for your comment. It is always a pleasure to hear that people like something I created as a passion project.

I'm glad you like API. I did spend a lot of time considering the interface. If I had known from the beginning how people would be using I might've designed a more efficient bytecode interpreter because its way of tokenizing and interpreting the file line by line (and then doing it again if there are loops) is very inefficient.

Also, I only found out afterwards that there's also a libc implementation called Musl which is much more popular than my Musl, but I figured I didn't need to rename my project because nobody uses it ;-)

I'd like to take you up on your offer. You can find my contact details in my profile.

Cheers,
Werner
